app/urls.py
from django.urls import path
import dappstore.event_watcher
from . import views
from threading import Thread

app_name = "app"

urlpatterns = [
    path("", views.home, name="home"),
    path("feedback/<str:name>", views.feedback, name="feedback"),
]

thread = Thread(target=dappstore.event_watcher.loop)
thread.daemon = True
thread.start()

dappstore/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("", include("app.urls")),
    path('admin/', admin.site.urls),
]

app/models.py
from django.db import models

ratings = [(r, r) for r in range(0, 6)]


class Dapp(models.Model):
    name = models.CharField(max_length=1000)
    address = models.CharField(max_length=1000, null=True, blank=True)  # submission owner
    status = models.CharField(max_length=1000)
    category = models.CharField(max_length=1000)
    homepage = models.CharField(max_length=1000)
    icon = models.CharField(max_length=1000, null=True, blank=True)
    blockchain = models.CharField(max_length=1000)
    current_fund = models.IntegerField(default=0)
    fund_next_stage = models.IntegerField(default=10)
    days_to_go = models.IntegerField(default=10)


class State(models.Model):
    key = models.CharField(max_length=1000, primary_key=True)
    value = models.IntegerField()


class Feedback(models.Model):
    dapp = models.ForeignKey(Dapp, on_delete=models.CASCADE)
    text = models.CharField(max_length=1000)
    rating = models.CharField(max_length=1, choices=ratings, default=0)

app/forms.py
from django import forms

from .models import ratings


class FeedbackForm(forms.Form):
    name = forms.CharField(max_length=1000)  # dapp name
    text = forms.CharField(max_length=1000, widget=forms.Textarea(attrs={"class": "form-control"}))
    rating = forms.ChoiceField(choices=ratings, widget=forms.RadioSelect())

app/views.py
from django.shortcuts import render
from random import randint

from .forms import FeedbackForm
from .models import Dapp, Feedback

st = {
    "prototype": "mvp",
    "mvp": "alpha",
    "alpha": "beta",
    "beta": "live",
    "live": None
}
def home(request):
    if request.method == "POST":
        add = int(request.POST.get("eth"))
        name = request.POST.get("name")
        print(name, add)
        x = Dapp.objects.all().filter(name__exact=name)[0]
        x.current_fund += add
        #x.current_fund = 0
        if x.current_fund >= x.fund_next_stage:
            x.status = st[x.status.lower()]
            x.fund_next_stage += randint(10, 30)
        x.save()

    dapps = Dapp.objects.all()
    prototypes = dapps.filter(status__iexact="prototype")
    mvps = dapps.filter(status__iexact="mvp")
    alphas = dapps.filter(status__iexact="alpha")
    betas = dapps.filter(status__iexact="beta")
    lives = dapps.filter(status__iexact="live")
    context = {
        "prototypes": prototypes,
        "mvps": mvps,
        "alphas": alphas,
        "betas": betas,
        "lives": lives,
        "title": "Welcome to The dAppMap!",
    }
    return render(request, "home.html", context)


def feedback(request, name):
    dapp = Dapp.objects.all().filter(name__iexact=name)[0]
    form = FeedbackForm()
    if request.method == "POST":
        form = FeedbackForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data["name"]
            text = form.cleaned_data["text"]
            rating = form.cleaned_data["rating"]
            f = Feedback(dapp=dapp, text=text, rating=rating)
            f.save()

    feedbacks = Feedback.objects.all().filter(dapp__exact=dapp)

    context = {
        "form": form,
        "name": name,
        "feedbacks": feedbacks,
    }
    return render(request, "feedback.html", context)

app/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    {# Required meta tags #}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {# Bootstrap CSS #}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">

    <title>{{ title }}</title>
      <style>
.checked {
    color: orange;
}
</style>
  </head>
  <body>
    <nav class="navbar navbar-dark bg-primary">
      <h1 style="color:white;">dAppMap</h1>
    </nav>
    <div style="background-color: red; color: white; padding-left: 30px">This project is a showcase, it contains dummy data.</div>
    {% block content %}{% endblock %}

    <div id="footer" class="container-fluid bg-dark text-light">
      <div class="container">
        <div class="col text-center">
          <p>
            The DappStore is free open-source software: <a href="https://github.com/dappstore0/dappstore">https://github.com/dappstore0/dappstore</a>
          </p>
        </div>
      </div>
    </div>

    {# Optional JavaScript #}
    {# jQuery first, then Popper.js, then Bootstrap JS #}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

app/templates/dapp.html
<div class="dapp text-center">
    {% if dapp.days_to_go < 14 %}
    <div style="background-color: #FF6666">
        <p style="color: black"><b>{{ dapp.days_to_go }}</b> days to go<br>
    </div>
    {% elif dapp.days_to_go < 60 %}
        <div style="background-color: #FFFF66">
        <p style="color: black"><b>{{ dapp.days_to_go }}</b> days to go<br>
    </div>
    {% else %}
        <div style="background-color: #B2FF66">
        <p style="color: black"><b>{{ dapp.days_to_go }}</b> days to go<br>
    </div>
    {% endif %}
  <h3>
    {{ dapp.name }}
    <br>
    <span class="label"><i class="fas fa-tag"></i> {{ dapp.category }}</span>
  </h3>

  <img height="60px" src="{{ dapp.icon }}">
  <br>

  <a href="{{ dapp.homepage }}">{{ dapp.homepage }}</a>

   <!-- <div style="background-color: #343a40">
        <p style="color: white"><b>28</b> days to go<br>
        <b>45</b> days to deliver</p>
    </div>
    -->
    <p>Funding {{ dapp.current_fund }} / {{ dapp.fund_next_stage }} ETH</p>
  <form action="/" method="post">
    {% csrf_token %}
    <input type="hidden" name="name" value="{{ dapp.name }}">
    <input class="form-control text-center" type="number" name="eth" min="0" max="{{ dapp.fund_next_stage }}" step="1" value="5"><br>
    <button class="btn btn-primary" type="submit" onclick="alert('You received 50 {{ dapp.name }} tokens')">Fund</button>
  </form>
  <br>
<span class="fa fa-star checked"></span>
<span class="fa fa-star checked"></span>
<span class="fa fa-star checked"></span>
<span class="fa fa-star checked"></span>
<span class="fa fa-star"></span>
  <a href="{% url "app:feedback" dapp.name %}">
    <button type="button" class="btn btn-success">Give Feedback</button>
  </a>
</div>

app/templates/feedback.html
{% extends "base.html" %}
{% load static %}


{% block content %}
  <link rel="stylesheet" href="{% static "style.css" %}">
  <br>
  <div class="container">
    <div class="row navbar navbar-dark bg-dark">
      <h2 style="color:white;">Feedback</h2>
    </div>
    <br>
    {% for feedback in feedbacks %}
      <div class="feedback">
        <div class="row">
          <div class="col-10">
            {{ feedback.text }}
          </div>
          <div class="col-2">
            Rating: {{ feedback.rating }}
          </div>
        </div>
      </div>
    {% endfor %}
    <br>
    <div class="row navbar navbar-dark bg-dark">
      <h3 style="color:white;">Submit your Feedback</h3>
    </div>
    <br>
    <div class="row">
      <div class="col">
        <form action="{% url "app:feedback" name %}" method="post">
          {% csrf_token %}
          {{ form.non_field_errors }}
          <div class="field">
            {{ form.text.errors }}
            {{ form.text.label_tag }}
            {{ form.text }}
          </div>
          <br>
          <div class="field">
            {{ form.rating.errors }}
            {{ form.rating.label_tag }}
            {{ form.rating }}
          </div>
          <input type="hidden" name="name" value="{{ name }}">
          <button class="btn btn-success btn-sm">Submit</button>
        </form>
        <br>
      </div>
    </div>
  </div>
{% endblock %}

app/templates/home.html
{% extends "base.html" %}
{% load static %}


{% block content %}
  <link rel="stylesheet" href="{% static "style.css" %}">
  <br>
  <div class="container">
    <div class="row navbar navbar-dark bg-dark">
      <h2 style="color:white;">Prototype</h2>
    </div>
    <br>
    <div class="row">
      {% for prototype in prototypes %}
        <div class="col-md-3">
          {% include "dapp.html" with dapp=prototype %}
        </div>
      {% endfor %}
    </div>
    <br>
    <div class="row navbar navbar-dark bg-dark">
      <h2 style="color:white;">MVP</h2>
    </div>
    <br>
    <div class="row">
      {% for mvp in mvps %}
        <div class="col-md-3">
          {% include "dapp.html" with dapp=mvp %}
        </div>
      {% endfor %}
    </div>

    <br>
    <div class="row navbar navbar-dark bg-dark">
      <h2 style="color:white;">Alpha</h2>
    </div>
    <br>
    <div class="row">
      {% for alpha in alphas %}
        <div class="col-md-3">
          {% include "dapp.html" with dapp=alpha %}
        </div>
      {% endfor %}
    </div>
    <br>
    <div class="row navbar navbar-dark bg-dark">
      <h2 style="color:white;">Beta</h2>
    </div>
    <br>
    <div class="row">
      {% for beta in betas %}
        <div class="col-md-3">
          {% include "dapp.html" with dapp=beta %}
        </div>
      {% endfor %}
    </div>
    <br>
    <div class="row navbar navbar-dark bg-dark">
      <h2 style="color:white;">Live</h2>
    </div>
    <br>
    <div class="row">
      {% for live in lives  %}
        <div class="col-md-3">
          {% include "dapp.html" with dapp=live %}
        </div>
      {% endfor %}
    </div>
  </div>
  <br>
{% endblock %}